"""add_backtest_detail_analytics_columns

Revision ID: 1c9c073277cf
Revises: 55d1b020a048
Create Date: 2026-07-02 15:01:14.299088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9c073277cf'
down_revision: Union[str, Sequence[str], None] = '55d1b020a048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winning_trades', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('losing_trades', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('avg_win', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('avg_loss', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('expectancy', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('sortino_ratio', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('calmar_ratio', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_column('calmar_ratio')
        batch_op.drop_column('sortino_ratio')
        batch_op.drop_column('expectancy')
        batch_op.drop_column('avg_loss')
        batch_op.drop_column('avg_win')
        batch_op.drop_column('losing_trades')
        batch_op.drop_column('winning_trades')

    # ### end Alembic commands ###
