"""add smc scanner tables

Revision ID: 9e03ebc5e743
Revises: 2b6f9a4d1e73
Create Date: 2026-07-12 14:27:43.691915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e03ebc5e743'
down_revision: Union[str, Sequence[str], None] = '2b6f9a4d1e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smc_scanner_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('max_signals_per_week', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smc_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit_1', sa.Float(), nullable=False),
    sa.Column('take_profit_2', sa.Float(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason_note', sa.Text(), nullable=False),
    sa.Column('score_breakdown_json', sa.Text(), nullable=False),
    sa.Column('candle_time', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('paired_trade_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smc_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smc_signals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_smc_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_smc_signals_symbol_status', ['symbol', 'status'], unique=False)

    op.create_table('smc_watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('last_scanned_candle_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', name='uq_smc_watch_symbol_interval')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smc_watchlist')
    with op.batch_alter_table('smc_signals', schema=None) as batch_op:
        batch_op.drop_index('ix_smc_signals_symbol_status')
        batch_op.drop_index(batch_op.f('ix_smc_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_smc_signals_status'))

    op.drop_table('smc_signals')
    op.drop_table('smc_scanner_settings')
    # ### end Alembic commands ###
